<?php
/**
 * Faq Categories List
 *
 * @var $block \Infobeans\Faq\Block\Sidebar\Category
 */
?>
<?php $items = $this->getCategories(); ?>

<?php if (count($items)) {  
    
    ?>

<div class="faq-category"> 
    
	<ul>
	<?php
		$i = 0;		 
		foreach($items as $item) { 
                    if($i==0)
                    {
                        $currentCategory=$item->getId(); 
                    }
                    
                    ?>
			 
            <li id="cat<?php echo $item->getId();?>" <?php echo ($i == 0)?'class="active"':''?> >
                        <a  href="javascript:;" <?php echo ($i == 0)?'class="disableClick"':''?> onclick="fetchFaq('<?php echo $item->getId();?>',1)">
			    <?php echo $block->escapeHtml($item->getCategoryName()) ?>
			</a>
	        <?php
		$i++;	 
		}
   	?>
	</ul>
</div>
<input type="hidden" id="current-category" value="<?php echo $currentCategory;?>" />
<?php } ?>
<script>
 function fetchFaq(categoryId,page){
        require([
            'jquery',
            'jquery/ui'
        ], function($){ 
           
            $.ajax({
                    url: "<?php echo $this->getBaseUrl(); ?>faq/ajax/index",
                    method: 'POST',
                    showLoader: true,
                    data: { 
                        category_id: categoryId,
                        page:page,                        
                    },
                    success: function (response) {
                    $('.faq-category li').removeClass('active');   
                    $('.faq-category li a').removeClass('disableClick');   
                    $("#accordion").accordion("destroy"); 
                    $('#faq-list').html(response);
                    $('.pager .item').removeClass('current');                    
                    $('.pager .page'+page).addClass('current');
                    $('#current-category').val(categoryId);    
                    $("#accordion").accordion({ 
                        heightStyle: "content"
                     });
                     
                     $('#cat'+categoryId).addClass('active');
                     $('#cat'+categoryId+' a').addClass('disableClick');
                    }
                });
            
        });

    }
    
    
    
    
    
</script>    